[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[build.env]
PYTHON_VERSION = "3.11.5"