[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "PYTHONPATH=/app python main.py"
healthcheckPath = "/"  # Cambia a la ruta raíz
healthcheckTimeout = 180  # Aumenta el timeout
restartPolicyType = "on_failure"

[build.env]
PYTHON_VERSION = "3.11.5"